### ISSUE TITLE
Supporting Tower 3.2.x

### ISSUE THREAD

**Issue by jameswnl** [ManageIQ/manageiq-providers-ansible_tower#53]
# Credentials
## Major Changes
* Tower 3.2.x upgrade will split up a machine credential which has vault_password value and both will remain associated to job_templates (if any)
** For us, we'll create/update accordingly (have to test and confirm if the new machine credential will keep the original ID.
* Tower 3.2.x upgrade will drop azure_classic and rackspace credentials (and previously associated job_templates will just lose them
** https://github.com/ManageIQ/manageiq/pull/16936 and #58 
** After upgrade, refresh will destroy them
* Other newly added: 
** Vault
** Ansible Tower
** Insights
** rhev
** custom credential type (Custom credentials will not be managed by the V1 API)

## Todo

- [x] UI changes for embedded Ansible items will need a new credential drop-down for Vault.  (
  - [x] Services Template: https://github.com/ManageIQ/manageiq-ui-classic/pull/3468
  - [x] Automate Method Type: (Same as above)
- [x] Add Vault credential in Service summary screen
  - [x] https://github.com/ManageIQ/manageiq/pull/17207
  - [x] https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/70
- [x] Back-end: Add vault credential support to Ansible playbook service template https://github.com/ManageIQ/manageiq/pull/17184
- [x] Back-end: Add vault credential support to Ansible Automate Method Type https://github.com/ManageIQ/manageiq/pull/17192
- [x] Clarify if upgrade and split machine credential will keep the original ID
  - [ ] Test the upgrade scenario
- [x] Provider code changes
  - [x] vault credential type
    - [x] PR https://github.com/ManageIQ/manageiq/pull/16825
    - [x] PR https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/54
  - [x] rhev credential type
    - this can be only partially supported through the Tower API V1
    - The support for the optional field `ca file location` can only be done when move to consume from API V2
    - [x] PR https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/62
    - [x] PR https://github.com/ManageIQ/manageiq/pull/17044
    - [x] PR https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/69
  - [x] drop Rackspace/Azure Classic credential types
    - [x] PR https://github.com/ManageIQ/manageiq/pull/16936
    - [x] PR https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/58

## Others

* Investigate usage of custom credential (e.g. supporting `Azure classic`?)

**Comment by jameswnl** [comment]
@gmcculloug @bdunne @syncrou

**Comment by gmcculloug** [comment]
@jameswnl Thanks for capturing these notes.

I would suggest adding an item in the **Todo** section for "will machine credential will keep the original ID".  Also, I assume there is work to enable the UI to CRUD the new Vault credentials.  From what I understand this is backend work, but you would know better.

Another item, but maybe not a Todo here is to investigate custom credentials more so we can support types like Azure through this new feature.

**Comment by gmcculloug** [comment]
<img width="796" alt="screen_shot_2018-02-21_at_1_18_48_pm" src="https://user-images.githubusercontent.com/2591569/36497988-f76adbe8-170a-11e8-9a23-6eed1b9535b4.png">

**Comment by gmcculloug** [comment]
@jameswnl I think we have addressed all the areas here, if you agree I think we can close this issue.

**Comment by jameswnl** [comment]
@gmcculloug I've added a todo to test the upgrade scenario and its impact on the converted/dropped credentials.
